/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.magna.swing.java.swing.signup;

/**
 *
 * @author Gustavo
 */
public class TotemSignup extends javax.swing.JFrame {

    /**
     * Creates new form Signup
     */
    public TotemSignup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblHostname = new javax.swing.JLabel();
        fieldHostname = new javax.swing.JTextField();
        separatorHostname = new javax.swing.JSeparator();
        lblLocalizacao = new javax.swing.JLabel();
        fieldLocalizacao = new javax.swing.JTextField();
        separatorLocalizacao = new javax.swing.JSeparator();
        lblSenha = new javax.swing.JLabel();
        separatorSenha = new javax.swing.JSeparator();
        fieldSenha = new javax.swing.JPasswordField();
        btnSignupTotem = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        bannerMagna = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(32, 33, 35));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        lblHostname.setBackground(new java.awt.Color(255, 255, 255));
        lblHostname.setForeground(new java.awt.Color(255, 255, 255));
        lblHostname.setText("Nome da máquina");

        fieldHostname.setBackground(new java.awt.Color(32, 33, 35));
        fieldHostname.setForeground(new java.awt.Color(255, 255, 255));
        fieldHostname.setBorder(null);
        fieldHostname.setCaretColor(new java.awt.Color(255, 255, 255));
        fieldHostname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldHostnameActionPerformed(evt);
            }
        });

        separatorHostname.setBackground(new java.awt.Color(255, 255, 255));
        separatorHostname.setForeground(new java.awt.Color(255, 255, 255));

        lblLocalizacao.setBackground(new java.awt.Color(255, 255, 255));
        lblLocalizacao.setForeground(new java.awt.Color(255, 255, 255));
        lblLocalizacao.setText("Localização");

        fieldLocalizacao.setBackground(new java.awt.Color(32, 33, 35));
        fieldLocalizacao.setForeground(new java.awt.Color(255, 255, 255));
        fieldLocalizacao.setBorder(null);
        fieldLocalizacao.setCaretColor(new java.awt.Color(255, 255, 255));
        fieldLocalizacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldLocalizacaoActionPerformed(evt);
            }
        });

        separatorLocalizacao.setBackground(new java.awt.Color(255, 255, 255));
        separatorLocalizacao.setForeground(new java.awt.Color(255, 255, 255));

        lblSenha.setBackground(new java.awt.Color(255, 255, 255));
        lblSenha.setForeground(new java.awt.Color(255, 255, 255));
        lblSenha.setText("Senha");

        separatorSenha.setBackground(new java.awt.Color(255, 255, 255));
        separatorSenha.setForeground(new java.awt.Color(255, 255, 255));

        fieldSenha.setBackground(new java.awt.Color(32, 33, 35));
        fieldSenha.setForeground(new java.awt.Color(255, 255, 255));
        fieldSenha.setBorder(null);
        fieldSenha.setCaretColor(new java.awt.Color(255, 255, 255));
        fieldSenha.setDisabledTextColor(new java.awt.Color(255, 255, 255));

        btnSignupTotem.setBackground(new java.awt.Color(2, 216, 240));
        btnSignupTotem.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnSignupTotem.setForeground(new java.awt.Color(0, 0, 0));
        btnSignupTotem.setText("CADASTRAR MÁQUINA");
        btnSignupTotem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignupTotemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(btnSignupTotem, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fieldSenha)
                    .addComponent(separatorSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(lblSenha)
                    .addComponent(separatorHostname)
                    .addComponent(lblHostname)
                    .addComponent(fieldHostname, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(separatorLocalizacao)
                    .addComponent(lblLocalizacao)
                    .addComponent(fieldLocalizacao, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(lblHostname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldHostname, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separatorHostname, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(lblLocalizacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldLocalizacao, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separatorLocalizacao, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(lblSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separatorSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(btnSignupTotem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(90, 90, 90));

        bannerMagna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/magna-banner.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bannerMagna, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(bannerMagna, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldHostnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldHostnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldHostnameActionPerformed

    private void fieldLocalizacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldLocalizacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldLocalizacaoActionPerformed

    private void btnSignupTotemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignupTotemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSignupTotemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TotemSignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TotemSignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TotemSignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TotemSignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TotemSignup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bannerMagna;
    private javax.swing.JButton btnSignupTotem;
    private javax.swing.JTextField fieldHostname;
    private javax.swing.JTextField fieldLocalizacao;
    private javax.swing.JPasswordField fieldSenha;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblHostname;
    private javax.swing.JLabel lblLocalizacao;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JSeparator separatorHostname;
    private javax.swing.JSeparator separatorLocalizacao;
    private javax.swing.JSeparator separatorSenha;
    // End of variables declaration//GEN-END:variables
}
