/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package swing.signup;
<<<<<<< HEAD
=======

import external.Network;
import java.net.Inet4Address;
import java.net.InetAddress;
>>>>>>> 3df25c40c5e6762fd7852d7a3f2c6349e411f64c

/**
 *
 * @author gustavo.moraes@VALEMOBI.CORP
 */
public class ComputerRegister extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public ComputerRegister() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblTitle1 = new javax.swing.JLabel();
        lblTitle2 = new javax.swing.JLabel();
        lblLocalhost = new javax.swing.JLabel();
        userLocalHost = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        lblOperationalSystem = new javax.swing.JLabel();
        userOperationalSystem = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        btnSignUp = new javax.swing.JButton();
        lblOperationalSystem1 = new javax.swing.JLabel();
        userLocalization1 = new javax.swing.JTextField();
        lblLocalization1 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(32, 33, 35));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel4.setForeground(new java.awt.Color(60, 63, 65));
<<<<<<< HEAD
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/magna_banner.jpg"))); // NOI18N
=======
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/magna-banner.jpg"))); // NOI18N
>>>>>>> 3df25c40c5e6762fd7852d7a3f2c6349e411f64c
        jLabel4.setText("jLabel4");

        jPanel2.setBackground(new java.awt.Color(32, 33, 35));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle1.setBackground(new java.awt.Color(240, 240, 240));
        lblTitle1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblTitle1.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle1.setText("Verificamos que essa máquina não está cadastrada,");
        jPanel2.add(lblTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        lblTitle2.setBackground(new java.awt.Color(240, 240, 240));
        lblTitle2.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblTitle2.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle2.setText("faça o cadastro da mesma para utilizar o sistema.");
        jPanel2.add(lblTitle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        lblLocalhost.setBackground(new java.awt.Color(240, 240, 240));
        lblLocalhost.setForeground(new java.awt.Color(57, 113, 117));
        lblLocalhost.setText("Nome da Máquina");
        jPanel2.add(lblLocalhost, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, -1, 20));

        userLocalHost.setBackground(new java.awt.Color(32, 33, 35));
        userLocalHost.setForeground(new java.awt.Color(255, 255, 255));
        userLocalHost.setBorder(null);
        userLocalHost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userLocalHostActionPerformed(evt);
            }
        });
        jPanel2.add(userLocalHost, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 340, 20));

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 340, -1));

        lblOperationalSystem.setBackground(new java.awt.Color(240, 240, 240));
        lblOperationalSystem.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(lblOperationalSystem, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, -1, 20));

        userOperationalSystem.setBackground(new java.awt.Color(32, 33, 35));
        userOperationalSystem.setForeground(new java.awt.Color(255, 255, 255));
        userOperationalSystem.setActionCommand("<Not Set>");
        userOperationalSystem.setBorder(null);
        userOperationalSystem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userOperationalSystemActionPerformed(evt);
            }
        });
        jPanel2.add(userOperationalSystem, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 340, 20));
        userOperationalSystem.getAccessibleContext().setAccessibleName("");
        userOperationalSystem.getAccessibleContext().setAccessibleDescription("");

        jSeparator6.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 340, -1));

        btnSignUp.setBackground(new java.awt.Color(0, 200, 255));
        btnSignUp.setFont(new java.awt.Font("Noto Mono", 1, 15)); // NOI18N
        btnSignUp.setForeground(new java.awt.Color(10, 10, 10));
        btnSignUp.setText("CADASTRAR MÁQUINA");
        btnSignUp.setBorder(null);
        btnSignUp.setBorderPainted(false);
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });
        jPanel2.add(btnSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, 340, 40));

        lblOperationalSystem1.setBackground(new java.awt.Color(240, 240, 240));
        lblOperationalSystem1.setForeground(new java.awt.Color(57, 113, 117));
        lblOperationalSystem1.setText("Sistema Operacional");
        jPanel2.add(lblOperationalSystem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, -1, 20));

        userLocalization1.setBackground(new java.awt.Color(32, 33, 35));
        userLocalization1.setForeground(new java.awt.Color(255, 255, 255));
        userLocalization1.setBorder(null);
        userLocalization1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userLocalization1ActionPerformed(evt);
            }
        });
        jPanel2.add(userLocalization1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 340, 20));

        lblLocalization1.setBackground(new java.awt.Color(240, 240, 240));
        lblLocalization1.setForeground(new java.awt.Color(57, 113, 117));
        lblLocalization1.setText("Localização");
        jPanel2.add(lblLocalization1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, -1, 20));

        jSeparator7.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 340, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userLocalHostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userLocalHostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userLocalHostActionPerformed

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSignUpActionPerformed

    private void userOperationalSystemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userOperationalSystemActionPerformed
        
    }//GEN-LAST:event_userOperationalSystemActionPerformed

    private void userLocalization1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userLocalization1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userLocalization1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComputerRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComputerRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComputerRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComputerRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editora

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComputerRegister().setVisible(true);
                new ComputerRegister().userOperationalSystem.setText("aaaaaaa");
                new ComputerRegister().userOperationalSystem.getText();

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSignUp;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel lblLocalhost;
    private javax.swing.JLabel lblLocalization1;
    private javax.swing.JLabel lblOperationalSystem;
    private javax.swing.JLabel lblOperationalSystem1;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblTitle2;
    public javax.swing.JTextField userLocalHost;
    private javax.swing.JTextField userLocalization1;
    public javax.swing.JTextField userOperationalSystem;
    // End of variables declaration//GEN-END:variables
}
