<<<<<<< HEAD
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package swing.signup;

import database.connection.Connection;
=======
package swing.signup;

import database.connectiondb.Connection;
import database.table.Totem;
>>>>>>> 3df25c40c5e6762fd7852d7a3f2c6349e411f64c
import external.Network;
import java.net.InetAddress;
import java.net.SocketException;
import java.net.UnknownHostException;
import java.util.List;
import org.springframework.jdbc.core.BeanPropertyRowMapper;
import org.springframework.jdbc.core.JdbcTemplate;

<<<<<<< HEAD
/**
 *
 * @author gustavo.moraes@VALEMOBI.CORP
 */
public class LoginScreen extends javax.swing.JFrame {
=======
public class LoginScreen extends javax.swing.JFrame {
    ComputerRegister computerRegister = new ComputerRegister();
>>>>>>> 3df25c40c5e6762fd7852d7a3f2c6349e411f64c
    /**
     * Creates new form Home
     */
    public LoginScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
<<<<<<< HEAD
        lblEmail = new javax.swing.JLabel();
        userEmail1 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        lblPass = new javax.swing.JLabel();
        userPass = new javax.swing.JPasswordField();
=======
        userPass = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        password = new javax.swing.JPasswordField();
>>>>>>> 3df25c40c5e6762fd7852d7a3f2c6349e411f64c
        jSeparator4 = new javax.swing.JSeparator();
        btnSignUp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(32, 33, 35));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel4.setForeground(new java.awt.Color(60, 63, 65));
<<<<<<< HEAD
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/magna_banner.jpg"))); // NOI18N
=======
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/magna-banner.jpg"))); // NOI18N
>>>>>>> 3df25c40c5e6762fd7852d7a3f2c6349e411f64c
        jLabel4.setText("jLabel4");

        jPanel2.setBackground(new java.awt.Color(32, 33, 35));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEmail.setBackground(new java.awt.Color(240, 240, 240));
        lblEmail.setForeground(new java.awt.Color(57, 113, 117));
        lblEmail.setText("Email");
        jPanel2.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, 20));

        email.setBackground(new java.awt.Color(32, 33, 35));
        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setBorder(null);
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel2.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 340, 20));

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 340, -1));

<<<<<<< HEAD
        lblPass.setBackground(new java.awt.Color(240, 240, 240));
        lblPass.setForeground(new java.awt.Color(57, 113, 117));
        lblPass.setText("Senha");
        jPanel2.add(lblPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, 20));

        userPass.setBackground(new java.awt.Color(32, 33, 35));
        userPass.setForeground(new java.awt.Color(255, 255, 255));
        userPass.setBorder(null);
        userPass.setCaretColor(new java.awt.Color(255, 255, 255));
        userPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userPassActionPerformed(evt);
            }
        });
        jPanel2.add(userPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 340, 20));
=======
        password.setBackground(new java.awt.Color(32, 33, 35));
        password.setForeground(new java.awt.Color(255, 255, 255));
        password.setBorder(null);
        password.setCaretColor(new java.awt.Color(255, 255, 255));
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        jPanel2.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 340, 20));
>>>>>>> 3df25c40c5e6762fd7852d7a3f2c6349e411f64c

        jSeparator4.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 340, -1));

        btnSignUp.setBackground(new java.awt.Color(0, 200, 255));
        btnSignUp.setFont(new java.awt.Font("Noto Mono", 1, 15)); // NOI18N
        btnSignUp.setForeground(new java.awt.Color(10, 10, 10));
        btnSignUp.setText("ENTRAR");
        btnSignUp.setBorder(null);
        btnSignUp.setBorderPainted(false);
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    btnSignUpActionPerformed(evt);
                } catch (UnknownHostException e) {
<<<<<<< HEAD
                    throw new RuntimeException(e);
                } catch (SocketException e) {
                    throw new RuntimeException(e);
=======
                    e.printStackTrace();
                } catch (SocketException e) {
                    e.printStackTrace();
>>>>>>> 3df25c40c5e6762fd7852d7a3f2c6349e411f64c
                }
            }
        });
        jPanel2.add(btnSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 340, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) throws UnknownHostException, SocketException {//GEN-FIRST:event_btnSignUpActionPerformed
        String myPass = String.valueOf(password.getPassword());
        Network net = new Network();
        InetAddress addr = InetAddress.getLocalHost();


        
        Connection config = new Connection();
        JdbcTemplate con = new JdbcTemplate(config.getDataSource());
        
        
        if (email.getText().equals("admin@gmail.com") && myPass.equals("g123")) {
            this.dispose();
            
//            MacAddress mac = new MacAddress();
//            String sql = "SELECT * FROM network WHERE mac = ?";
//            if (mac.getMAC().equals()) {
//
//            }

            computerRegister.userOperationalSystem.setText(System.getProperty("os.name"));
            computerRegister.setVisible(true);
            computerRegister.userOperationalSystem.setEditable(false);

            computerRegister.userLocalHost.setText(net.getLocalHost());
            computerRegister.userLocalHost.setEditable(false);
            
            con.update(
                "INSERT INTO TOTEM VALUES(null, ?, ?, ?, ?, ?)",
                "Segundo andar", "Rodando", System.getProperty("os.name")
                , computerRegister.userLocalHost.getText(), net.getMac(addr));
        
        }
       

<<<<<<< HEAD
    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) throws UnknownHostException, SocketException {//GEN-FIRST:event_btnSignUpActionPerformed
        ComputerRegister computerRegister = new ComputerRegister();
        String passwordGetText = new String(userPass.getPassword());
        Network net = new Network();
        
        Connection config = new Connection();
        JdbcTemplate con = new JdbcTemplate(config.getDataSource());
        
        if (userEmail1.getText().equals("admin@gmail.com") && passwordGetText.equals("123")) {
            InetAddress addr = InetAddress.getLocalHost();
            
            this.dispose();
            computerRegister.setVisible(true);
            
            con.update("INSERT INTO totem VALUES (?, ?, ?, ?)",
                null, "Primeiro andar", "Rodando", net.getMAC(addr), net.getLocalHost());
            
        }

=======
>>>>>>> 3df25c40c5e6762fd7852d7a3f2c6349e411f64c
        

    }//GEN-LAST:event_btnSignUpActionPerformed

<<<<<<< HEAD
    private void userPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userPassActionPerformed
=======
    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed
>>>>>>> 3df25c40c5e6762fd7852d7a3f2c6349e411f64c

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSignUp;
<<<<<<< HEAD
=======
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel3;
>>>>>>> 3df25c40c5e6762fd7852d7a3f2c6349e411f64c
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
<<<<<<< HEAD
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblPass;
    private javax.swing.JTextField userEmail1;
    private javax.swing.JPasswordField userPass;
=======
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel userPass;
>>>>>>> 3df25c40c5e6762fd7852d7a3f2c6349e411f64c
    // End of variables declaration//GEN-END:variables
}
